services:
  db:
    image: postgis/postgis:14-3.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: primary_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment: &env
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/primary_db
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app

  ingestion:
    build: ./ingestion
    container_name: ingestion
    depends_on:
      - db
    environment:
      <<: *env
      GET_HISTORICAL: "true"
      MIGRATE_DB: "true"
      REALTIME_FETCH_INTERVAL: 300
    develop:
      watch:
        - action: sync
          path: ./ingestion
          target: /app

volumes:
  db_data: